Add files via upload

diff --git a/Configs/nnn/plugins/finder b/Configs/nnn/plugins/finder
--- a/Configs/nnn/plugins/finder
+++ b/Configs/nnn/plugins/finder
@@ -1,85 +1,89 @@
 #!/usr/bin/env sh
 
-# Description: Regular mode:
-#                Fuzzy find a file in directory subtree.
-#                Opens in $VISUAL or $EDITOR if text.
-#                Opens other type of files with xdg-open.
-#                Work only with a single file selected.
+# Description: Fuzzy search multiple locations read-in from a path-list file
+#              (or $PWD) and open the selected file's dir in a smart context.
+# Dependencies: fzf, find (only for multi-location search)
 #
-#              Picker mode:
-#                If picker mode output file is passed, it
-#                will be overwritten with any picked files.
-#                Leaves untouched if no file is picked.
-#                Works with single/multiple files selected.
+# Details: Paths in list file should be newline-separated absolute paths.
+#          Paths can be file paths; the script will scan the parent dirs.
 #
-# Dependencies: fd/find, fzf/skim, xdg-open/open (on macOS)
+#          The path-list file precedence is:
+#          - "$1" (the hovered file) if it exists, is plain-text and the
+#                 first line points to an existing file
+#          - "$LIST" if set below
+#          - "$2" (the current directory) [mimics plugin fzcd behaviour]
+#
+#          The path-list file can be generated easily:
+#          - pick the (file)paths in picker mode to path-list file
+#          - OR, edit selection in nnn and save as path-list file
 #
 # Shell: POSIX compliant
-# Author: Arun Prakash Jana
+# Author: Anna Arad, Arun Prakash Jana, KlzXS
 
-NUKE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"
-USE_NUKE=0
+IFS="$(printf '\n\r')"
 
 # shellcheck disable=SC1090,SC1091
 . "$(dirname "$0")"/.nnn-plugin-helper
 
-if type fzf >/dev/null 2>&1; then
-    cmd="$FZF_DEFAULT_COMMAND"
-    if type fd >/dev/null 2>&1; then
-        [ -z "$cmd" ] && cmd="fd -t f 2>/dev/null"
-    else
-        [ -z "$cmd" ] && cmd="find . -type f 2>/dev/null"
-    fi
-    entry="$(eval "$cmd" | fzf -m)"
-    # To show only the file name
-    # entry=$(find . -type f 2>/dev/null | fzf --delimiter / --with-nth=-1 --tiebreak=begin --info=hidden)
-elif type sk >/dev/null 2>&1; then
-	entry=$(find . -type f 2>/dev/null | sk)
-else
+CTX=+
+LIST="${LIST:-""}"
+
+if ! type fzf >/dev/null 2>&1; then
+    printf "fzf missing"
+    read -r _
     exit 1
 fi
 
-# Check for picker mode
-if [ "$3" ]; then
-    if [ "$entry" ]; then
-        case "$entry" in
-            /*) fullpath="$entry" ;;
-            *)  fullpath="$PWD/$entry" ;;
-        esac
-        if [ "-" = "$3" ]; then
-            printf "%s\n" "$fullpath"
-        else
-            printf "%s\n" "$fullpath" > "$3"
-        fi
+if [ -n "$1" ] && [ "$(file -b --mime-type "$1")" = 'text/plain' ] && [ -e "$(head -1 "$1")" ]; then
+    LIST="$1"
+elif ! [ -s "$LIST" ]; then
+    sel=$(fzf)
+    # Show only the file and parent dir
+    # sel=$(fzf --delimiter / --with-nth=-2,-1 --tiebreak=begin --info=hidden)
 
-        # Tell `nnn` to clear its internal selection
-        printf "%s" "0p" > "$NNN_PIPE"
-    fi
-
-    exit 0
+    LIST=''
 fi
 
-if [ "$entry" ]; then
-    if [ "$USE_NUKE" -ne 0 ]; then
-        "$NUKE" "$entry"
+if [ -n "$LIST" ]; then
+    if type find >/dev/null 2>&1; then
+        tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
+
+        while IFS= read -r path; do
+            if [ -d "$path" ]; then
+                printf "%s\n" "$path" >> "$tmpfile"
+            elif [ -f "$path" ]; then
+                printf "%s\n" "$(dirname "$path")" >> "$tmpfile"
+            fi
+        done < "$LIST"
+
+        sel=$(xargs -d '\n' < "$tmpfile" -I{} find {} -type f -printf "%H//%P\n" | sed '/.*\/\/\(\..*\|.*\/\..*\)/d; s:/\+:/:g' | fzf --delimiter / --tiebreak=begin --info=hidden)
+        # Alternative for 'fd'
+        # sel=$(xargs -d '\n' < "$tmpfile" fd . | fzf --delimiter / --tiebreak=begin --info=hidden)
+
+        rm -- "$tmpfile"
+    else
+        printf "find missing"
+        read -r _
+            exit 1
+    fi
+fi
+
+if [ -n "$sel" ]; then
+    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
         exit 0
     fi
 
-    # Open the file (works for a single file only)
-    cmd_file=""
-    cmd_open=""
-    if uname | grep -q "Darwin"; then
-        cmd_file="file -bIL"
-        cmd_open="open"
-    else
-        cmd_file="file -biL"
-        cmd_open="xdg-open"
-    fi
+    # Check if the selected path returned by fzf command is absolute
+    case $sel in
+    /*) nnn_cd "$sel" "$CTX" ;;
+    *)
+        # Remove "./" prefix if it exists
+        sel="${sel#./}"
 
-    case "$($cmd_file "$entry")" in
-        *text*)
-            "${VISUAL:-$EDITOR}" "$entry" ;;
-        *)
-            $cmd_open "$entry" >/dev/null 2>&1 ;;
+        if [ "$PWD" = "/" ]; then
+            nnn_cd "/$sel" "$CTX"
+        else
+            nnn_cd "$PWD/$sel" "$CTX"
+        fi;;
     esac
 fi
