Add files via upload

diff --git a/Configs/lf/lfrc b/Configs/lf/lfrc
--- a/Configs/lf/lfrc
+++ b/Configs/lf/lfrc
@@ -167,32 +167,25 @@ cmd toggle-mount $~/.config/lf/nmount $fx
 cmd compress $~/.config/lf/compress $fx
 
 cmd extract ${{
-set -f
 
-# Check if there are any selected files
-if [ -z "$fx" ]; then
-  echo "No files selected."
-  exit 1
-fi
+	# Check if there are any selected files
+	if [ -z "$fx" ]; then
+ 	 echo "No files selected."
+  	exit 1
+	fi
 
-for f in $fx; do
-  case $f in
-    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2)
-      tar xjvf "$f" && lf -remote "send $id :reload" ;;
-    *.tar.gz|*.tgz)
-      tar xzvf "$f" && lf -remote "send $id :reload" ;;
-    *.tar.xz|*.txz)
-      tar xJvf "$f" && lf -remote "send $id :reload" ;;
-    *.tar.zst|*.tzst)
-      tar -xvf "$f" && lf -remote "send $id :reload" ;;
-    *.zip)
-      unzip "$f" && lf -remote "send $id :reload" ;;
-    *.rar)
-      unrar x "$f" && lf -remote "send $id :reload" ;;
-    *.7z)
-      7z x "$f" && lf -remote "send $id :reload" ;;
-  esac
+	for f in $fx; do
+	case $f in
+		*.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf "$f" ;;
+		*.tar.gz|*.tgz) tar xzvf "$f" ;;
+		*.tar.xz|*.txz) tar xJvf "$f" ;;
+		*.tar.zst|*.tzst) tar -xvf "$f" ;;
+		*.zip) unzip "$f" ;;
+		*.rar) unrar x "$f" ;;
+		*.7z) 7z x "$f" ;;
+		*) echo -e "Failed to extract '$f'..." ;;
+	esac
+	[ $? -eq 0 ] && lf -remote "send $id :reload"
 done
 
 }}
-
